filterbank:
  fb_name: sfi_fdmgf
  n_filters: 512
  kernel_size: 64
  stride: 32
  n_samples: 640
  init_type: erb
  initial_freq_range: [50.0, 16000.0]
  trainable: true
  one_sided: false
  init_sigma: 251.32741228718345 # 40*2.0*numpy.pi
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  conv_kernel_size: 3
  hid_chan: 512
# Training config
training:
  epochs: 100
  batch_size: 4
  num_workers: 4
  half_lr: yes
  half_lr_parameter:
    factor: 0.5
    patience: 2
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/2speakers/wav32k/min/tr/
  valid_dir: data/2speakers/wav32k/min/cv/
  n_src: 2
  sample_rate: 32000
  segment: 0.5
# other config
other:
  seed: 39